blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('all/', views.show_all_posts, name='show-all-posts'),
    path('create/', views.create_post, name='create-post'),
    path('create-category/', views.CreateCategory.as_view(), name='create-category'),
    path('update-category/<int:pk>/', views.UpdateCategory.as_view(), name='update-category'),
    path('like-post/<int:id>', views.like_post, name='like-post'),
    path('edit/<int:pk>', views.edit_post, name='edit'),
    path('post/<int:pk>', views.ViewPost.as_view(), name='detail'),
    path('category/<slug:category_slug>/', views.FilterPostByCategory.as_view(), name='post-by-category'),
]

djangol1/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from blog.views import show_all_posts
from store import views as store_view
from users import views as user_view

router = DefaultRouter()
router.register('user', user_view.UserViewSet)
router.register('orders', store_view.OrderViewSet)
router.register('store/order-items', store_view.OrderItemViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('users/', include('users.urls')),
    path('inventory/', include('inventory.urls')),
    path('store/', include('store.urls')),
    path('', show_all_posts, name='home'),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/', include(router.urls)),
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page

app_name = 'inventory'
urlpatterns = [
    path('', views.ListProductView.as_view(), name='list'),
    path('<int:pk>', cache_page(60 * 5)(views.DetailProductView.as_view()), name='detail'),
    path('api/v1/', views.ProductList.as_view())
]

store/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

app_name = 'store'
urlpatterns = [
    path('add-to-cart/<int:product_id>', views.add_to_cart, name='add-to-cart'),
    path('cart/', views.view_cart, name='view-cart'),
    path('delete/<int:product_id>', views.delete_row, name='delete-row'),
    path('deduct/', views.deduct_from_cart, name='deduct-from-cart'),
    path('finalize/', views.finalize_order, name='finalize'),
    path('list-orders/', views.ListOrdersView.as_view(), name='list-orders'),
    path('print/<int:pk>', views.PrintOrder.as_view(), name='print-order'),
]

users/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from . import views


app_name = 'users'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/edit/', views.EditUserProfile.as_view(), name='edit-profile'),
]

blog/models.py
from django.db import models


class Post(models.Model):
    """
    Represents a single blog post
    """
    created_date = models.DateTimeField(verbose_name='تاریخ ایجاد', auto_now_add=True)
    creator = models.ForeignKey('auth.User', verbose_name='کاربر', on_delete=models.PROTECT)
    content = models.TextField(verbose_name='متن', null=True)
    title = models.CharField(max_length=100, verbose_name='عنوان پست')
    intro_image = models.ImageField(verbose_name='عکس مقدمه پست', blank=True, null=True)
    likes = models.IntegerField(default=0)
    categories = models.ManyToManyField('blog.Category')

    class Meta:
        ordering = ('title',)
        verbose_name = 'پست'
        verbose_name_plural = 'پست ها'

    def __str__(self):
        return f'{self.title}'


class Category(models.Model):
    """
    Categories for posts
    """
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=20, unique=True, null=False, blank=False)

    class Meta:
        permissions = []
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from . import models


class CalcForm(forms.Form):
    """
    Form for calculator
    """
    pass


class PostForm(forms.ModelForm):
    """
    Model form for Post model
    """

    class Meta:
        model = models.Post
        fields = [
            'title',
            'content',
            'intro_image',
            'categories'
        ]

blog/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import JsonResponse, HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.views.generic import CreateView, DetailView, UpdateView, ListView

from . import models, forms


def show_all_posts(request):
    """
    This view will show all of the posts
    """
    if request.user.is_authenticated:
        my_posts = models.Post.objects.filter(creator=request.user)
        other_posts = models.Post.objects.exclude(creator=request.user)
    else:
        my_posts = models.Post.objects.all()
        other_posts = []
    return render(
        request=request,
        context={
            'object_list': my_posts,
            'object_list_2': other_posts,
            'page_title': 'Show all posts'
        },
        template_name='blog/all_posts.html'
    )


@login_required
def create_post(request):
    """
    Creates a post
    """

    if not request.user.has_perm('blog.add_post'):
        raise PermissionDenied('Access denied.')

    form_instance = forms.PostForm()

    if request.method == 'POST':
        form_instance = forms.PostForm(data=request.POST, files=request.FILES)
        if form_instance.is_valid():
            form_instance.instance.creator = request.user
            form_instance.save()
            return redirect('blog:show-all-posts')

    return render(request, 'blog/post_form.html', {
        'form': form_instance,
        'page_title': 'Create a new post'
    })


def edit_post(request, pk):
    """
    Edit a single post
    """
    post_instance = get_object_or_404(klass=models.Post, pk=pk)

    if not post_instance.creator == request.user:
        return HttpResponseForbidden('Access denied.')
    if not request.user.has_perm('blog.change_post'):
        raise PermissionDenied()

    if request.method == 'POST':
        form_instance = forms.PostForm(
            instance=post_instance,
            data=request.POST,
            files=request.FILES
        )
        if form_instance.is_valid():
            form_instance.save()
            messages.success(request, 'Saved successfully.')
            return redirect('blog:show-all-posts')
    else:
        # The GET method
        form_instance = forms.PostForm(instance=post_instance)
        return render(
            request,
            context={
                'form': form_instance,
                'page_title': f'Edit post #{post_instance.pk}'
            },
            template_name='blog/post_form.html'
        )


@require_POST
@csrf_exempt
def like_post(request, id):
    """
    Increments post's like field
    """
    result = False

    # Main logic
    post_obj = get_object_or_404(klass=models.Post, pk=id)
    post_obj.likes += 1
    post_obj.save()
    result = True

    # Response
    return JsonResponse({'result': result, 'likes': post_obj.likes})


class CreateCategory(PermissionRequiredMixin, CreateView):
    model = models.Category
    fields = (
        'name',
        'slug'
    )
    success_url = reverse_lazy('blog:show-all-posts')
    extra_context = {
        'page_title': 'Create a category'
    }
    permission_required = 'blog.add_category'


class UpdateCategory(PermissionRequiredMixin, UpdateView):
    model = models.Category
    fields = (
        'name', 'slug'
    )
    success_url = reverse_lazy('blog:show-all-posts')
    permission_required = 'blog.change_category'


class ViewPost(DetailView):
    model = models.Post


class FilterPostByCategory(ListView):
    model = models.Post
    template_name = 'blog/all_posts.html'

    def get_queryset(self):
        category_slug = self.kwargs.get('category_slug', None)
        qs = super().get_queryset()
        qs = qs.filter(categories__slug=category_slug)
        return qs

blog/templates/blog/all_posts.html
{% extends 'blog/base.html' %}
{% load static %}
{% block page_header_title %}
    نمایش همه پست ها
{% endblock %}
{% block content %}
    <div class="col-2">
        <h5>Filter by category:</h5>
        <ul>
            {% for category in category_list %}
                <li>
                    <a href="{% url 'blog:post-by-category' category.0 %}">{{ category.0 }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="col-10 row justify-content-md-left">
        {% for post in object_list %}
            {# One single post #}
            <div class="col-4 mb-4">
                {% if post.intro_image %}
                    <a href="{% url 'blog:detail' post.pk %}">
                        <img src="{{ post.intro_image.url }}" class="img-thumbnail">
                    </a>
                {% else %}
                    <a href="{% url 'blog:detail' post.pk %}">
                        <img src="{% static 'img/placeholder.png' %}" class="img-thumbnail">
                    </a>
                {% endif %}
                <h3 class="">
                    <a href="{% url 'blog:detail' post.pk %}">{{ post.title }}</a>
                </h3>
                <h6>{{ post.created_date }} By {{ post.creator.username }}</h6>
                <strong>{{ post.creator.first_name }} {{ post.creator.last_name }}</strong>
                <p>{{ post.content|truncatewords:10 }}</p>
                {# Like button for the post #}
                <a class="btn btn-outline-dark text-danger like-btn" data-post-id="{{ post.id }}">❤ Like (<span id="like-count-{{ post.id }}">{{ post.likes }}</span> Likes)</a>
            </div>
        {% endfor %}
        {% for post in object_list_2 %}
            {# One single post #}
            <div class="col-4 mb-4">
                {% if post.intro_image %}
                    <a href="{% url 'blog:detail' post.pk %}">
                        <img src="{{ post.intro_image.url }}" class="img-thumbnail">
                    </a>
                {% else %}
                    <a href="{% url 'blog:detail' post.pk %}">
                        <img src="{% static 'img/placeholder.png' %}" class="img-thumbnail">
                    </a>
                {% endif %}
                <h3 class="">
                    <a href="{% url 'blog:detail' post.pk %}">{{ post.title }}</a>
                </h3>
                <h6>{{ post.created_date }} By {{ post.creator.username }}</h6>
                <strong>{{ post.creator.first_name }} {{ post.creator.last_name }}</strong>
                <p>{{ post.content|truncatewords:10 }}</p>
                {# Like button for the post #}
                <a class="btn btn-outline-dark text-danger like-btn" data-post-id="{{ post.id }}">❤ Like (<span id="like-count-{{ post.id }}">{{ post.likes }}</span> Likes)</a>
            </div>
        {% endfor %}
    </div>
{% endblock %}
{% block page_scripts %}
    <script>
        $(document).ready(function () {
            $('.like-btn').on('click', function (event) {
                var postId = $(event.target)[0].dataset.postId;
                $.ajax({
                    url: '/blog/like-post/' + postId,
                    method: 'POST',
                    success: function (response) {
                        var likes = response.likes;
                        $('#like-count-' + postId).html(likes);
                    }
                });
            });
        });
    </script>
{% endblock %}

blog/templates/blog/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/all.css' %}" rel="stylesheet">
    <title>
        My Blog:
        {% block page_header_title %}
            {{ page_title }}
        {% endblock %}
    </title>
</head>
<body>
<div class="container">
    <nav class="navbar rounded navbar-expand-md navbar-dark bg-success">
        <a class="navbar-brand" href="/">Home</a>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Login
                            <span class="sr-only"></span></a>
                    </li>
                {% endif %}
                {% if perms.blog.add_post %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:create-post' %}">Create Post
                            <span class="sr-only">(current)</span></a>
                    </li>
                {% endif %}
                {% if perms.blog.add_category %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:create-category' %}">
                            Create Category
                        </a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'inventory:list' %}">
                        🎁 Products
                    </a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'store:list-orders' %}">
                        orders🧺
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'store:view-cart' %}">
                        sabad kharid 🛒
                    </a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Logout 👋🏻
                            <span class="sr-only"></span></a>
                    </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:edit-profile' %}">
                            {{ request.user.get_full_name }}
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    {# Django's messages #}
    <div class="row mt-3 mb-3">
        <div class="col-12">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-danger alert-dismissible">
                        {{ message }}
                        <button type="button" data-dismiss="alert" class="close">&times;</button>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    {# django's messages ends #}
    <div class="row mb-4 mt-4">
        {% block content %}YOUR CONTENT GOES HERE{% endblock %}
    </div>
</div>
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

{% block page_scripts %}{% endblock %}

<footer class="footer">
    <div class="container">
        <span class="text-muted">Copyright &copy; {{ year }}</span>
    </div>
</footer>
<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }
</style>
</body>
</html>

blog/templates/blog/category_form.html
{% extends 'blog/base.html' %}
{% block page_header_title %}
    🆕 {{ page_title }}
{% endblock %}
{% block content %}
    <div class="col-12">
        <h3>{{ page_title }}</h3>
        <form method="post">
            {% csrf_token %}
            {% with field=form.name %}
                <div class="form-group">
                    <label for="{{ field.auto_id }}">{{ field.label }}</label>
                    <input type="text" id="{{ field.auto_id }}" class="form-control" value="{{ field.initial }}" name="{{ field.name }}">
                </div>
            {% endwith %}
            {% with field=form.slug %}
                <div class="form-group">
                    <label for="{{ field.auto_id }}">{{ field.label }}</label>
                    <input type="text" id="{{ field.auto_id }}" class="form-control" value="{{ field.initial }}" name="{{ field.name }}">
                </div>
            {% endwith %}
            <button type="submit" class="btn btn-primary">💾 Save</button>
        </form>
    </div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block page_header_title %}
    Post: {{ object.title }}
{% endblock %}
{% block content %}
    <div class="col-12">
        {% if object.intro_image %}
            <img src="{{ object.intro_image.url }}" class="img-fluid" alt="{{ object.intro_image.name }}">
        {% endif %}
        <div class="d-flex">
            <h1>{{ object.title }}</h1>
            {% if request.user.is_authenticated %}
                {% if post.creator == request.user %}
                    <a href="{% url 'blog:edit' post.pk %}" class="float-left">✏</a>
                {% endif %}
            {% endif %}
        </div>
        <h3>Created by: {{ object.creator.get_full_name }}</h3>
        <h4>Created on: {{ object.created_date }}</h4>
        <hr>
        <p>{{ object.content }}</p>
    </div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% load widget_tweaks %}
{% block page_header_title %}
    🆕 {{ page_title }}
{% endblock %}
{% block content %}
    <div class="col-12">
        <h3>{{ page_title }}</h3>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="title">عنوان پست</label>
                {#                <input type="text" id="title" class="form-control" value="{{ form.initial.title }}" name="title">#}
                {{ form.title|add_class:'form-control' }}
            </div>
            <div class="form-group">
                <label for="content">متن پست</label>
                {#                <textarea name="content" id="content" cols="50" rows="10" class="form-control">{{ form.initial.content }}</textarea>#}
                {{ form.content | add_class:'form-control' | attr:"cols:50" | attr:"rows:10" }}
            </div>
            <div class="form-group">
                {{ form.intro_image }}
            </div>
            <div class="form-group">
                {{ form.categories }}
            </div>
            <button type="submit" class="btn btn-primary">💾 Save</button>
        </form>
    </div>
{% endblock %}