blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('all/', views.show_all_posts, name='show-all-posts'),
    path('create/', views.create_post, name='create-post'),
    path('create-category/', views.CreateCategory.as_view(), name='create-category'),
    path('update-category/<int:pk>/', views.UpdateCategory.as_view(), name='update-category'),
    path('like-post/<int:id>', views.like_post, name='like-post'),
    path('edit/<int:pk>', views.edit_post, name='edit'),
    path('post/<int:pk>', views.ViewPost.as_view(), name='detail'),
    path('category/<slug:category_slug>/', views.FilterPostByCategory.as_view(), name='post-by-category'),
]

djangol1/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from blog.views import show_all_posts
from store import views as store_view
from users import views as user_view

router = DefaultRouter()
router.register('user', user_view.UserViewSet)
router.register('orders', store_view.OrderViewSet)
router.register('store/order-items', store_view.OrderItemViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('users/', include('users.urls')),
    path('inventory/', include('inventory.urls')),
    path('store/', include('store.urls')),
    path('', show_all_posts, name='home'),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/', include(router.urls)),
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page

app_name = 'inventory'
urlpatterns = [
    path('', views.ListProductView.as_view(), name='list'),
    path('<int:pk>', cache_page(60 * 5)(views.DetailProductView.as_view()), name='detail'),
    path('api/v1/', views.ProductList.as_view())
]

store/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

app_name = 'store'
urlpatterns = [
    path('add-to-cart/<int:product_id>', views.add_to_cart, name='add-to-cart'),
    path('cart/', views.view_cart, name='view-cart'),
    path('delete/<int:product_id>', views.delete_row, name='delete-row'),
    path('deduct/', views.deduct_from_cart, name='deduct-from-cart'),
    path('finalize/', views.finalize_order, name='finalize'),
    path('list-orders/', views.ListOrdersView.as_view(), name='list-orders'),
    path('print/<int:pk>', views.PrintOrder.as_view(), name='print-order'),
]

inventory/models.py
from django.db import models
from django.utils.translation import ugettext as _
from . import enums
from django.core.cache import cache


class Product(models.Model):
    """
    Represents a single product
    """
    name = models.CharField(
        max_length=200,
        verbose_name=_('نام کالا'),
        db_index=True
    )
    description = models.TextField(
        verbose_name=_('توضحیات محصول'),
        help_text='متن نمایشی برای توصیف محصول'
    )
    price = models.PositiveIntegerField(default=0, db_index=True, verbose_name=_('قیمت'))
    qty_in_stock = models.PositiveIntegerField(default=0, verbose_name=_('تعداد'))
    is_active = models.BooleanField(
        default=False,
        help_text='آیا این محصول فروخته میشود؟',
        verbose_name=_('آیا فعال است؟')
    )
    type = models.CharField(
        max_length=100,
        choices=enums.ProductTypes.choices,
        verbose_name=_('نوع محصول')
    )

    class Meta:
        verbose_name = _('کالا')
        verbose_name_plural = _('کالاها')

    def __str__(self):
        return self.name

    def can_be_sold(self):
        return self.is_active

    def is_in_stock(self, qty):
        return qty <= self.qty_in_stock

    def get_prices(self, qty):
        key = f'price{self.pk}{qty}'
        val = cache.get(key)
        if val is None:
            price = self.price * qty
            cache.set(key, price)
            return price
        return val

    def deduct_from_stock(self, qty):
        """
        Deducts the qty from self.qty_in_stock
        returns: int
        """
        self.qty_in_stock -= qty
        self.save()
        return self.qty_in_stock

inventory/views.py
from django.views.generic import ListView, DetailView
from rest_framework import generics

from . import models, serializers


class ListProductView(ListView):
    """
    Shows a list of active products
    """
    paginate_by = 10
    queryset = models.Product.objects.filter(
        is_active=True
    )


class DetailProductView(DetailView):
    model = models.Product
    template_name = 'inventory/detail-product.html'


class ProductList(generics.ListAPIView):
    queryset = models.Product.objects.filter(is_active=True)
    serializer_class = serializers.ProductSerializer

inventory/templates/inventory/detail-product.html
{% extends 'blog/base.html' %}
{% block content %}
    <div class="container">
        <h1>{{ product.name }}</h1>
        <h5>Description : {{ product.description }}</h5>
        <h5>Price : {{ product.price }}</h5>
        <h5>Stock left : {{ product.qty_in_stock }}</h5>
        <h5>Type : {{ product.type }}</h5>
    </div>
{% endblock %}

inventory/templates/inventory/product_list.html
{% extends 'blog/base.html' %}
{% block content %}
    <div class="container">
        <table>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Price</th>
                <th>Stock</th>
                <th>Type</th>
                <th>Order</th>
            </tr>
            {% for product in object_list %}
                <tr>
                    <th><a href="{% url 'inventory:detail' product.pk %}">{{ product.name }}</a> </th>
                    <th>{{ product.description | truncatewords:5 }}</th>
                    <th>{{ product.price }}</th>
                    <th>{{ product.qty_in_stock }}</th>
                    <th>{{ product.type }}</th>
                    <th><a href="{% url 'store:add-to-cart' product.pk %}" class="btn btn-dark rounded">🛒 order</a></th>
                </tr>
            {% endfor %}
        </table>
        <br>
        <div class="text-center">
            <span class="step-links align-items-center">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
        </div>
    </div>
{% endblock %}