blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('all/', views.show_all_posts, name='show-all-posts'),
    path('create/', views.create_post, name='create-post'),
    path('create-category/', views.CreateCategory.as_view(), name='create-category'),
    path('update-category/<int:pk>/', views.UpdateCategory.as_view(), name='update-category'),
    path('like-post/<int:id>', views.like_post, name='like-post'),
    path('edit/<int:pk>', views.edit_post, name='edit'),
    path('post/<int:pk>', views.ViewPost.as_view(), name='detail'),
    path('category/<slug:category_slug>/', views.FilterPostByCategory.as_view(), name='post-by-category'),
]

djangol1/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from blog.views import show_all_posts
from store import views as store_view
from users import views as user_view

router = DefaultRouter()
router.register('user', user_view.UserViewSet)
router.register('orders', store_view.OrderViewSet)
router.register('store/order-items', store_view.OrderItemViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('users/', include('users.urls')),
    path('inventory/', include('inventory.urls')),
    path('store/', include('store.urls')),
    path('', show_all_posts, name='home'),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/', include(router.urls)),
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

app_name = 'store'
urlpatterns = [
    path('add-to-cart/<int:product_id>', views.add_to_cart, name='add-to-cart'),
    path('cart/', views.view_cart, name='view-cart'),
    path('delete/<int:product_id>', views.delete_row, name='delete-row'),
    path('deduct/', views.deduct_from_cart, name='deduct-from-cart'),
    path('finalize/', views.finalize_order, name='finalize'),
    path('list-orders/', views.ListOrdersView.as_view(), name='list-orders'),
    path('print/<int:pk>', views.PrintOrder.as_view(), name='print-order'),
]

store/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import Sum
from django_jalali.db import models as jmodels
from django.utils.translation import ugettext as _
from . import enums
from .signals import order_placed
import logging

logger = logging.getLogger(__name__)


class OrderQuerySetManager(models.QuerySet):
    """
    Custom QuerySet Manager
    """

    def filter_by_owner(self, user):
        """
        Filters objects by owner field
        """
        return self.filter(owner=user)


class Order(models.Model):
    """
    Represents an order
    """
    owner = models.ForeignKey(get_user_model(), on_delete=models.PROTECT, verbose_name=_('ثبت کننده سفارش'))
    created_on = jmodels.jDateTimeField(auto_now_add=True, verbose_name=_('تاریخ ثبت'))
    status = models.CharField(
        verbose_name=_('وضعیت'),
        help_text='وضعیت سفارش',
        choices=enums.OrderStatuses.choices,
        default=enums.OrderStatuses.ACTIVE,
        max_length=100
    )
    objects = OrderQuerySetManager.as_manager()

    def __str__(self):
        if self.owner.get_full_name():
            name = self.owner.get_full_name()
        else:
            name = self.owner
        return f'Order #{self.pk} for {name}'

    def set_as_canceled(self):
        self.status = enums.OrderStatuses.CANCELED
        self.save()
        logger.info(f'order #{self.pk} was set as CANCELED .')

    def save(self, **kwargs):
        if self.pk is None:
            _created = True
        else:
            _created = False
        super().save(**kwargs)
        order_placed.send(sender=self.__class__, instance=self, created=_created)
        logger.debug(f'order_placed signal was send for order #{self.pk} .')

    def get_total_qty(self):
        return self.orderitem_set.aggregate(Sum('qty')).get('qty__sum', 0)

    def get_total_price(self):
        return self.orderitem_set.aggregate(Sum('price')).get('price__sum', 0)


class OrderItem(models.Model):
    """
    A single item in the order
    """
    order = models.ForeignKey('store.Order', on_delete=models.CASCADE)
    product = models.ForeignKey('inventory.Product', on_delete=models.PROTECT)
    qty = models.PositiveIntegerField(default=1)
    discount = models.FloatField(default=0)
    price = models.PositiveIntegerField()

    def get_total(self):
        return self.qty * self.price

store/views.py
import weasyprint
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.views.generic import ListView, DetailView
from rest_framework import viewsets, status
from rest_framework.decorators import action
from rest_framework.exceptions import NotAuthenticated

from . import models, serializers, permissions
import logging
from inventory import models as inventory_models

# Create your views here.
logger = logging.getLogger(__name__)


def add_to_cart(request, product_id):
    product_instance = get_object_or_404(inventory_models.Product, pk=product_id)

    if not product_instance.can_be_sold():
        messages.error(request, 'not for sell. ')
        return redirect('inventory:list')

    if not product_instance.is_in_stock(1):
        messages.error(request, 'out of stock.')
        return redirect('inventory:list')

    if 'cart' not in request.session.keys():
        request.session['cart'] = {
            # '1': 1
            # Product ID : Qty
        }

    if str(product_instance.pk) in request.session['cart'].keys():
        request.session['cart'][str(product_instance.pk)] += 1
    else:
        request.session['cart'][str(product_instance.pk)] = 1

    request.session.save()
    messages.success(request, f'{product_instance} be sabad kharid ezafe shod.')

    return redirect('inventory:list')


def view_cart(request):
    object_list = []
    for key, value in request.session.get('cart', {}).items():
        object_list += [
            {
                'product': inventory_models.Product.objects.get(pk=int(key)),
                'qty': value,
                'price': inventory_models.Product.objects.get(pk=int(key)).get_prices(value),
            }
        ]

    return render(
        request, 'view_cart.html', context={'object_list': object_list}
    )


def delete_row(request, product_id):
    request.session['cart'].pop(str(product_id), None)
    request.session.save()
    messages.success(request, 'delete!!!')
    return redirect('store:view-cart')


@require_POST
@csrf_exempt
def deduct_from_cart(request):
    """
    Deducts one from product's qty in the cart
    """
    product_id = request.POST.get('product_id', None)
    # What if there were not product_id provided?
    if not product_id:
        return JsonResponse({'success': False, 'error': 'Invalid data.'}, status=400)

    # Cast product_id to string
    product_id = str(product_id)

    # Try to deduct from qty
    try:
        request.session['cart'][product_id] -= 1
        request.session.modified = True
        return JsonResponse({'success': True, 'qty': request.session['cart'][product_id]}, status=200)
    except KeyError:
        # What if the product is not in the cart?
        return JsonResponse({'success': False, 'error': 'Invalid data. Not in the cart.'}, status=400)


class OrderViewSet(viewsets.ModelViewSet):
    """
    ViewSet for store.Order
    """
    queryset = models.Order.objects.all()
    serializer_class = serializers.OrderSerializer
    permission_classes = [permissions.IsOwner]

    def get_queryset(self):
        qs = super().get_queryset()
        if self.request.user.is_anonymous:
            raise NotAuthenticated('You need to be logged on.')
        return qs.filter_by_owner(self.request.user)

    @action(detail=True, description='Cancels an order')
    def cancel_order(self, request, *args, **kwargs):
        """
        Cancels an order
        """
        order_instance = self.get_object()
        order_instance.set_as_canceled()
        order_serializer = self.get_serializer(instance=order_instance)
        return JsonResponse(order_serializer.data, status=status.HTTP_202_ACCEPTED)


class OrderItemViewSet(viewsets.ModelViewSet):
    """
    ViewSet for store.OrderItem
    """
    queryset = models.OrderItem.objects.all()
    serializer_class = serializers.OrderItemSerializer
    permission_classes = [permissions.IsOwnerOfParent]



@login_required
def finalize_order(request):
    """
    Finalize order
    """
    cart = request.session.get('cart', None)

    # If cart does not exist or is empty
    if not cart:
        messages.error(request, 'سبد شما خالی است.')
        return redirect('inventory:list')

    order_instance = models.Order.objects.create(owner=request.user)

    for product_id in cart:
        product = inventory_models.Product.objects.get(pk=product_id)
        qty = cart[product_id]

        if not product.is_in_stock(qty):
            messages.error(request, 'کالا به تعداد درخواست شده موجود نیست.')
            return redirect('store:view-cart')

        models.OrderItem.objects.create(
            order=order_instance,
            qty=qty,
            product=product,
            price=product.get_prices(qty)
        )

        # Deduct from stock
        product.deduct_from_stock(qty)

    messages.info(request, 'سفارش با موفقیت ثبت شد.')
    request.session.pop('cart')
    request.session.modified = True
    logger.info(f"User #{request.user.pk} placed the order #{order_instance.pk}.")
    return redirect('inventory:list')


class ListOrdersView(LoginRequiredMixin, ListView):
    model = models.Order
    template_name = 'show_order.html'
    paginate_by = 5

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(owner=self.request.user)
        return qs


class PrintOrder(LoginRequiredMixin, DetailView):
    model = models.Order
    template_name = 'order_detail.html'

    def get(self, request, *args, **kwargs):
        default = super(PrintOrder, self).get(request, *args, **kwargs)
        rendered_content = default.rendered_content
        pdf = weasyprint.HTML(string=rendered_content).write_pdf()
        return HttpResponse(pdf, content_type='application/pdf')

store/templates/order_detail.html
<dl>
    <dt>نام خریدار</dt>
    <dd>{{ object.owner.get_full_name }}</dd>
    <dt>تاریخ سفارش</dt>
    <dd>{{ object.created_on.date }}</dd>
</dl>
<table>
    <thead>
    <tr>
        <th>ردیف</th>
        <th>نام کالا</th>
        <th>تعداد</th>
        <th>قیمت</th>
        <th>جمع</th>
    </tr>
    </thead>
    <tbody>
    {% for item in object.orderitem_set.all %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ item.prodcut }}</td>
            <td>{{ item.qty }}</td>
            <td>{{ item.price }} ریال</td>
            <td>{{ item.get_total }} ریال</td>
        </tr>
    {% endfor %}
    </tbody>
    <tfoot>
    <tr>
        <td colspan="3">
            {{ object.get_total_qty }}
        </td>
        <td colspan="2">
            مبلغ قابل پرداخت:
            {{ object.get_grand_total }}
            ریال
        </td>
    </tr>
    </tfoot>
</table>

store/templates/show_order.html
{% extends 'blog/base.html' %}
{% load i18n %}
{% block content %}
    <div class="container">
        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>{% trans 'شماره سفارش' %}</th>
                <th>{% trans 'تاریخ سفارش' %}</th>
                <th>وضعیت</th>
                <th>کالاها</th>
                <th> total qty </th>
                <th> total price </th>
            </tr>
            </thead>
            {% for order in object_list %}
                <tr>
                    <td>{{ order.pk }}</td>
                    <td>{{ order.created_on.date }} {{ order.created_on.time }}</td>
                    <td>{{ order.get_status_display }}</td>
                    <td>
                        {% for item in order.orderitem_set.all %}
                            <p style="direction: rtl;">
                                {{ forloop.counter }}- {{ item.product }} ❎ {{ item.qty }}
                            </p>
                        {% endfor %}
                    </td>
                    <td> {{ order.get_total_qty }}</td>
                    <td> {{ order.get_total_price }}</td>

                    <td>
                        <a href="{% url 'store:print-order' order.pk %}" class="btn btn-primary">
                            <i class="fa fa-print"></i>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <div class="text-center">
            <span class="step-links align-items-center">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}

                <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
                </span>
        </div>
    </div>
{% endblock %}

store/templates/view_cart.html
{% extends 'blog/base.html' %}
{% block content %}
    <div class="container">
    <table class="table table-striped">
        <thead>
        <tr>
            <th>ردیف</th>
            <th>کالا</th>
            <th>تعداد</th>
            <th>price</th>
            <th>حذف</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ object.product }}</td>
                <td>
                    <a class="deduct-btn btn btn-sm rounded btn-outline-danger btn-light mr-2" data-product-id="{{ object.product.pk }}">➖</a>
                    <span class="qty">{{ object.qty }}</span>
                    <a class="plus-btn btn btn-sm rounded btn-outline-success btn-light ml-2">➕</a>
                </td>
                <th>{{ object.price }}</th>
                <td><a href="{% url 'store:delete-row' object.product.pk %}" class="btn btn-outline-danger btn-sm">❌</a> </td>
            </tr>
        {% empty %}
            <tr>
            <td colspan="5" class="text-center">
                is empty!!!
            </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'store:finalize' %}" class="btn btn-primary float-right">
        🧺
        ثبت سفارش
    </a>
    </div>
{% endblock %}
{% block page_scripts %}
    <script>
        $(document).ready(function () {
            $('a.deduct-btn').click(function (event) {
                // Get the product id from the element that was clicked using
                // dataset attrib.
                const productId = event.currentTarget.dataset.productId;
                // Call the backends
                $.ajax({
                    url: "{% url 'store:deduct-from-cart' %}",
                    data: {
                        product_id: productId
                    },
                    method: 'post',
                    success: function (response) {
                         let qtySpan = $(event.currentTarget).next()[0];
                         qtySpan.innerHTML = response.qty;
                    },
                    error: function (response) {
                        console.log(response);
                        alert('حذف با خطا مواجه شد.')
                    }
                });
            });
        });
    </script>
{% endblock %}